services:
  web:
    build: .
    container_name: lideragestao-web
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /django_extrator/LideraGestao
    volumes:
      - .:/django_extrator/LideraGestao
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - scheduler

  scheduler:
    build: .
    container_name: lideragestao-scheduler
    working_dir: /django_extrator/LideraGestao
    volumes:
      - .:/django_extrator/LideraGestao
    command: ["python", "manage.py", "runjobs", "hourly"]
    env_file:
      - .env
    restart: always